FloatingBottle/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

home/urls.py
#-*-coding:utf-8 -*-

from django.urls import path, include, re_path
from .views import *
from django.contrib import admin


urlpatterns = [
    re_path('^$', index),
    path('index/', index),
    path('register/', register, name="register"),
    path('login/', login, name="login"),
    path('logout/', logout, name="logout"),

    # 个人中心
    path('user_info/', user_info, name="user_info"),
    path('change_userinfo/', change_userinfo, name="change_userinfo"),
    path('change_password/', change_password, name="change_password"),
    path('forget_password/', forget_password, name="forget_password"),
    path('send_code/', send_code, name="send_code"),

    # 公交信息
    path('bus_message/', bus_message, name="bus_message"),
    path('bus_detail/<int:id>', bus_detail, name="bus_detail"),

    # 站台管理
    path('site_message/', site_message, name="site_message"),
    path('site_detail/<int:id>', site_detail, name="site_detail"),

    # index ajax删除浏览历史
    path('del_history', del_history, name="del_history"),

]

app_name = "home"


from .add_data import *
# 数据添加接口
urlpatterns += [
    # path('add_bus_type/', add_bus_type, name="add_bus_type"),
    # path('add_bus/', add_bus, name="add_bus"),
    # path('add_site/', add_site, name="add_site"),
    # path('del_bus_site/', del_bus_site, name="del_bus_site"),
    # path('add_bus_site/', add_bus_site, name="add_bus_site"),
]

templates/common/bus_detail.html
{% extends "base/base.html" %}

{% block title %}
智能公交系统| 公交详情
{% endblock %}


{% block style %}
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800|Shadows+Into+Light" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="/static/assets/vendor/bootstrap/css/bootstrap.css" />
    <link rel="stylesheet" href="/static/assets/vendor/font-awesome/css/font-awesome.css" />
    <link rel="stylesheet" href="/static/assets/vendor/magnific-popup/magnific-popup.css" />
    <link rel="stylesheet" href="/static/assets/vendor/bootstrap-datepicker/css/datepicker3.css" />
    <link rel="stylesheet" href="/static/assets/stylesheets/theme.css" />
    <link rel="stylesheet" href="/static/assets/stylesheets/skins/default.css" />
    <link rel="stylesheet" href="/static/assets/stylesheets/theme-custom.css">
    <script src="/static/assets/vendor/modernizr/modernizr.js"></script>
    <style>
        td{color: black;}
    </style>
{% endblock %}


{% block content %}
    <header class="page-header">
        <h2>公交信息</h2>
        <div class="right-wrapper pull-right">
            <ol class="breadcrumbs">
                <li>
                    <a href="/">
                        <i class="fa fa-home"></i>
                    </a>
                </li>
                <li><span>公交信息</span></li>
                <li><span>{{ bus.bus_name }}详情</span></li>
            </ol>
            <a class="sidebar-right-toggle" data-open="sidebar-right"><i class="fa fa-chevron-left"></i></a>
        </div>
    </header>
    <div class="row">
    <div class="col-md-12">
    <section class="panel">
        <header class="panel-heading">
            <h2 class="panel-title">详细信息</h2>
        </header>
        <div class="panel-body">
            <a href="{% url 'home:bus_message' %}" class="btn btn-success">返回主页</a>
            <div class="table-responsive">
                <table class="table mb-none table-bordered">
                    <tbody>
                        <tr>
                            <td width="100px">公交名称：</td>
                            <td>{{ bus.bus_name }}</td>
                        </tr>
                        <tr>
                            <td>发车时间：</td>
                            <td>{{ bus.start_time }}</td>
                        </tr>
                        <tr>
                            <td>停运时间：</td>
                            <td>{{ bus.end_time }}</td>
                        </tr>
                        <tr>
                            <td>车票价钱：</td>
                            <td>{{ bus.money }}元</td>
                        </tr>
                        <tr>
                            <td>经过站点：</td>
                            <td>
                                <ul type="none">
                                    {% for site in s_list %}
                                    <li style="margin-top: 5px">
                                        <table>
                                            <tr> <td width="130px">{{ site.site_name }}</td>
                                        <td> {% if  site.bus_list %}
                                            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                            <i class="fa fa-bank" style="background-color: green;color: yellow"></i>
                                            &nbsp;可换乘：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                            {% for bus in site.bus_list  %}
                                                <a href="{% url 'home:bus_detail' bus.id %}" class="btn btn-sm btn-primary">
                                                    {{ bus.bus_name }}
                                                </a>
                                            {% endfor %}
                                        {% endif %}</td></tr>
                                        </table>
                                    </li>
                                    {% endfor %}
                                </ul>
                            </td>
                        </tr>
                        <tr>
                            <td>运营状态：</td>
                            <td>
                                {% if bus.status %}
                                <button type="button" class="btn btn-sm btn-success" } >
                                    运营中
                                </button>
                                {% else %}
                                    已停运
                                {% endif %}
                            </td>
                        </tr>
                        <tr>
                            <td>所属类型：</td>
                            <td>{{ bus.type }}</td>
                        </tr>
                        <tr>
                            <td>所属城市：</td>
                            <td>{{ bus.city }}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </section>
    </div>

    </div>

{% endblock %}


{% block script %}
    <script src="/static/assets/vendor/jquery/jquery.js"></script>
    <script src="/static/assets/vendor/jquery-browser-mobile/jquery.browser.mobile.js"></script>
    <script src="/static/assets/vendor/bootstrap/js/bootstrap.js"></script>
    <script src="/static/assets/vendor/nanoscroller/nanoscroller.js"></script>
    <script src="/static/assets/vendor/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>
    <script src="/static/assets/vendor/magnific-popup/magnific-popup.js"></script>
    <script src="/static/assets/vendor/jquery-placeholder/jquery.placeholder.js"></script>
    <script src="/static/assets/javascripts/theme.js"></script>
    <script src="/static/assets/javascripts/theme.custom.js"></script>
    <script src="/static/assets/javascripts/theme.init.js"></script>
{% endblock %}

templates/common/bus_message.html
{% extends "base/base.html" %}

{% block title %}
    智能公交系统 | 公交查询
{% endblock %}



{% block style %}
    <meta charset="UTF-8">
    <meta name="keywords" content="HTML5 Admin Template" />
    <meta name="description" content="Porto Admin - Responsive HTML5 Template">
    <meta name="author" content="okler.net">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800|Shadows+Into+Light" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="/static/assets/vendor/bootstrap/css/bootstrap.css" />
    <link rel="stylesheet" href="/static/assets/vendor/font-awesome/css/font-awesome.css" />
    <link rel="stylesheet" href="/static/assets/vendor/magnific-popup/magnific-popup.css" />
    <link rel="stylesheet" href="/static/assets/vendor/bootstrap-datepicker/css/datepicker3.css" />
    <link rel="stylesheet" href="/static/assets/stylesheets/theme.css" />
    <link rel="stylesheet" href="/static/assets/stylesheets/skins/default.css" />
    <link rel="stylesheet" href="/static/assets/stylesheets/theme-custom.css">
    <script src="/static/assets/vendor/modernizr/modernizr.js"></script>
    <style>
    .list li{float: left}
    </style>

{% endblock %}


{% block content %}
<header class="page-header">
    <h2>公交信息</h2>
    <div class="right-wrapper pull-right">
        <ol class="breadcrumbs">
            <li>
                <a href="/">
                    <i class="fa fa-home"></i>
                </a>
            </li>
            <li><span>公交信息</span></li>

        </ol>

        <a class="sidebar-right-toggle" data-open="sidebar-right"><i class="fa fa-chevron-left"></i></a>
    </div>
</header>

<div class="row">
    <div class="col-md-12">
    <section class="panel">
    <header class="panel-heading">
    <h2 class="panel-title">公交信息展示</h2>
    </header>
        <div class="panel-body">
        <div class="row">
            <div class="col-md-12">
                <div data-collapsed="0" class="panel">
                    <div class="panel-body">
                        <div class="row">
                            <form action="" method="get">
                                <div class="col-md-4 form-group">
                                    <input type="text" placeholder="公交类别" class="form-control" name="type_name" value="{{ type_name }}">
                                </div>
                                <div class="col-md-4 form-group">
                                    <input type="text" placeholder="公交名称" class="form-control" name="bus_name" value="{{ bus_name }}">
                                </div>
                                <div class="col-md-2 form-group">
                                    <button type="submit" class="form-control btn-primary btn">搜索</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="table-responsive">
            <table class="table table-hover mb-none">
                <thead>
                    <tr>
                        <th>公交名</th>
                        <th>出发站点</th>
                        <th>结束站点</th>
                        <th>发车时间</th>
                        <th>结束时间</th>
                        <th>所属类别</th>
                        <th>运营状态</th>
                    </tr>
                </thead>
                <tbody>
                {% for bus in data %}
                    <tr>
                        <td><a href="{% url 'home:bus_detail' bus.id %}" class="btn btn-primary btn-sm">{{ bus.bus_name }}</a></td>
                        <td>
                            {{ bus.bussite_set.first.site }}
                        </td>
                        <td>
                            {{ bus.bussite_set.last.site }}
                        </td>
                        <td>{{ bus.start_time }}</td>
                        <td>{{ bus.end_time }}</td>
                        <td>{{ bus.type }}</td>
                        <td>
                        {% if bus.status %}
                        <button type="button" class="btn btn-sm btn-success" } >
                            运营中
                        </button>
                        {% else %}
                            已停运
                        {% endif %}
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    </section>
    </div>
    <ul class="list">
       {% if data.has_previous %}
        <a href="?page={{ data.previous_page_number }}&type_name={{ type_name }}&bus_name={{ bus_name }}" class="btn-sm btn">&lt;</a>
        {% endif %}
        {% for page in page_list %}
            {% if request.GET.page %}
                {% if page == request.GET.page|add:0 %}
                    <a href="?page={{ page }}&type_name={{ type_name }}&bus_name={{ bus_name }}" class="btn-sm btn-success btn">{{ page }}</a>
                {% elif  request.GET.page|add:0 > data.number and page == 1%}
                    <a href="?page={{ page }}&type_name={{ type_name }}&bus_name={{ bus_name }}" class="btn-sm btn-success btn">{{ page }}</a>
                {% else %}
                    <a href="?page={{ page }}&type_name={{ type_name }}&bus_name={{ bus_name }}" class="btn-sm btn">{{ page }}</a>
                {% endif %}
            {% else %}
                 {% if page == 1 %}
                    <a href="?page={{ page }}&type_name={{ type_name }}&bus_name={{ bus_name }}" class="btn-sm btn-success btn">{{ page }}</a>
                    {% else %}
                    <a href="?page={{ page }}&type_name={{ type_name }}&bus_name={{ bus_name }}" class="btn-sm btn">{{ page }}</a>
                 {% endif %}
            {% endif %}
        {% endfor %}
         {% if data.has_next %}
            <a href="?page={{ data.next_page_number }}&type_name={{ type_name }}&bus_name={{ bus_name }}" class="btn-sm btn">&gt;</a>
         {% endif %}
    </ul>
</div>

{% endblock %}


{% block script %}
    <script src="/static/assets/vendor/jquery/jquery.js"></script>
    <script src="/static/assets/vendor/jquery-browser-mobile/jquery.browser.mobile.js"></script>
    <script src="/static/assets/vendor/bootstrap/js/bootstrap.js"></script>
    <script src="/static/assets/vendor/nanoscroller/nanoscroller.js"></script>
    <script src="/static/assets/vendor/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>
    <script src="/static/assets/vendor/magnific-popup/magnific-popup.js"></script>
    <script src="/static/assets/vendor/jquery-placeholder/jquery.placeholder.js"></script>
    <script src="/static/assets/javascripts/theme.js"></script>
    <script src="/static/assets/javascripts/theme.custom.js"></script>
    <script src="/static/assets/javascripts/theme.init.js"></script>
{% endblock %}

templates/common/forget_password.html
<!doctype html>
<html class="fixed">
	<head>
        
		<meta charset="UTF-8">
		<meta name="keywords" content="HTML5 Admin Template" />
		<meta name="description" content="Porto Admin - Responsive HTML5 Template">
		<meta name="author" content="okler.net">
		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
		<link href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800|Shadows+Into+Light" rel="stylesheet" type="text/css">
		<link rel="stylesheet" href="/static/assets/vendor/bootstrap/css/bootstrap.css" />
		<link rel="stylesheet" href="/static/assets/vendor/font-awesome/css/font-awesome.css" />
		<link rel="stylesheet" href="/static/assets/vendor/magnific-popup/magnific-popup.css" />
		<link rel="stylesheet" href="/static/assets/vendor/bootstrap-datepicker/css/datepicker3.css" />
		<link rel="stylesheet" href="/static/assets/stylesheets/theme.css" />
		<link rel="stylesheet" href="/static/assets/stylesheets/skins/default.css" />
		<link rel="stylesheet" href="/static/assets/stylesheets/theme-custom.css">
		<script src="/static/assets/vendor/modernizr/modernizr.js"></script>
	</head>
	<body>
		<section class="body-sign">
			<div class="center-sign">
				<a href="/" class="logo pull-left">
					<h1 style="color: black;">智能公交系统</h1>
				</a>
				<div class="panel panel-sign">
					<div class="panel-title-sign mt-xl text-right">
						<h2 class="title text-uppercase text-bold m-none"><i class="fa fa-user mr-xs"></i>重置密码</h2>
					</div>
					<div class="panel-body">
						<div class="alert alert-info">
							<p class="m-none text-semibold h4">输入邮箱接收验证码!</p>
						</div>
						<form method="post">
                            {% csrf_token %}
							<div class="form-group">
								<input name="email" id="email" type="email" placeholder="E-mail" class="form-control" />
                                <span id="message"></span>
                                <span style="color: red">{{ error }}</span>
							</div>
                            <div class="form-group">
								<button type="button" class="btn-primary btn btn-sm" onclick="f()">发送验证码</button>
							</div>
                            <div class="form-group">
								<input name="code" id="code" type="text" placeholder="验证码" class="form-control" />
							</div>
                            <div class="form-group">
								<input name="password" id="password" type="password" placeholder="密码" class="form-control" />
							</div>
                            <div class="form-group">
								<button type="submit" class="btn btn-warning">重置密码！</button>
							</div>
							<p class="text-center mt-lg">已有账号? <a href="{% url 'home:login' %}">去登录!</a>
						</form>
					</div>
				</div>

				<p class="text-center text-muted mt-md mb-md">&copy; Copyright 2020. All rights reserved. </p>
			</div>
		</section>
		<!-- end: page -->

		<!-- Vendor -->
		<script src="/static/assets/vendor/jquery/jquery.js"></script>
		<script src="/static/assets/vendor/jquery-browser-mobile/jquery.browser.mobile.js"></script>
		<script src="/static/assets/vendor/bootstrap/js/bootstrap.js"></script>
		<script src="/static/assets/vendor/nanoscroller/nanoscroller.js"></script>
		<script src="/static/assets/vendor/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>
		<script src="/static/assets/vendor/magnific-popup/magnific-popup.js"></script>
		<script src="/static/assets/vendor/jquery-placeholder/jquery.placeholder.js"></script>
		<script src="/static/assets/javascripts/theme.js"></script>
		<script src="/static/assets/javascripts/theme.custom.js"></script>
		<script src="/static/assets/javascripts/theme.init.js"></script>
        <script>
            function f() {
                var email = $("#email").val();
                if(email.length == 0){
                    window.alert("请输入邮箱！");
                    $("#email").focus();
                }
                console.log(email);
                $.ajax({
                    url:"/send_code",
                    data:{email:email},
                    type:"get",
                    dataType:"json",
                    success:function (data) {
                        console.log(data);
                        if(data.status==0){
                            $("#message").color = "red";
                            $("#message").css("color","red");
                        }
                        else{
                            $("#message").css("color", "green");
                        }
                        $("#message").html(data.data)
                    }
                })
            }
        </script>

	</body>
</html>

templates/common/map.html
{% extends "base/base.html" %}

{% block title %}

{% endblock %}



{% block style %}

{% endblock %}

{% block content %}



{% endblock %}


{% block script %}

{% endblock %}

templates/common/site_detail.html
{% extends "base/base.html" %}

{% block title %}
智能公交系统| 站台详情
{% endblock %}

{% block style %}
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800|Shadows+Into+Light" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="/static/assets/vendor/bootstrap/css/bootstrap.css" />
    <link rel="stylesheet" href="/static/assets/vendor/font-awesome/css/font-awesome.css" />
    <link rel="stylesheet" href="/static/assets/vendor/magnific-popup/magnific-popup.css" />
    <link rel="stylesheet" href="/static/assets/vendor/bootstrap-datepicker/css/datepicker3.css" />
    <link rel="stylesheet" href="/static/assets/stylesheets/theme.css" />
    <link rel="stylesheet" href="/static/assets/stylesheets/skins/default.css" />
    <link rel="stylesheet" href="/static/assets/stylesheets/theme-custom.css">
    <script src="/static/assets/vendor/modernizr/modernizr.js"></script>
    <style>
        td{color: black;}
    </style>
{% endblock %}


{% block content %}
    <header class="page-header">
        <h2>站台信息</h2>
        <div class="right-wrapper pull-right">
            <ol class="breadcrumbs">
                <li>
                    <a href="/">
                        <i class="fa fa-home"></i>
                    </a>
                </li>
                <li><span>站台信息</span></li>
                <li><span>站台详情</span></li>
            </ol>
            <a class="sidebar-right-toggle" data-open="sidebar-right"><i class="fa fa-chevron-left"></i></a>
        </div>
    </header>
    <div class="row">
    <div class="col-md-12">
    <section class="panel">
        <header class="panel-heading">
            <h2 class="panel-title">站台信息</h2>
        </header>
        <div class="panel-body">
            <a href="{% url 'home:site_message' %}" class="btn btn-success">返回主页</a>
            <div class="table-responsive">
                <table class="table mb-none">
                    <tbody>
                        <tr>
                            <td>站台名称：</td>
                            <td>{{ site.site_name }}</td>
                        </tr>
                        <tr>
                            <td>所属城市：</td>
                            <td>{{ site.city }}</td>
                        </tr>
                        <tr>
                            <td>路过车辆：</td>
                            <td>
                                <ul style="padding-left: 0;">
                                    {% for bus in site.bussite_set.all %}
                                    <li style="margin-top: 8px;" type="none">
                                        <table>
                                            <tr>
                                            <td>
                                                <i class="fa fa-automobile" style="background-color: green;color: yellow"></i>
                                                <a href="{% url 'home:bus_detail' bus.bus.id%}" class="btn btn-primary btn-sm">
                                                    {{ bus.bus.bus_name }}
                                                </a>&nbsp;&nbsp;{{ bus.bus.money }}元
                                            </td>
                                            </tr>
                                        </table>
                                    </li>
                                    {% endfor %}
                                </ul>
                            </td>
                        </tr>
                        <tr>
                            <td>站台编号：</td>
                            <td>{{ site.site_number }}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </section>
    </div>

    </div>

{% endblock %}


{% block script %}
    <script src="/static/assets/vendor/jquery/jquery.js"></script>
    <script src="/static/assets/vendor/jquery-browser-mobile/jquery.browser.mobile.js"></script>
    <script src="/static/assets/vendor/bootstrap/js/bootstrap.js"></script>
    <script src="/static/assets/vendor/nanoscroller/nanoscroller.js"></script>
    <script src="/static/assets/vendor/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>
    <script src="/static/assets/vendor/magnific-popup/magnific-popup.js"></script>
    <script src="/static/assets/vendor/jquery-placeholder/jquery.placeholder.js"></script>
    <script src="/static/assets/javascripts/theme.js"></script>
    <script src="/static/assets/javascripts/theme.custom.js"></script>
    <script src="/static/assets/javascripts/theme.init.js"></script>
{% endblock %}

templates/common/site_message.html
{% extends "base/base.html" %}

{% block title %}
    智能公交系统 | 站点查询
{% endblock %}



{% block style %}
    <meta charset="UTF-8">
    <title></title>
    <meta name="keywords" content="HTML5 Admin Template" />
    <meta name="description" content="Porto Admin - Responsive HTML5 Template">
    <meta name="author" content="okler.net">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800|Shadows+Into+Light" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="/static/assets/vendor/bootstrap/css/bootstrap.css" />
    <link rel="stylesheet" href="/static/assets/vendor/font-awesome/css/font-awesome.css" />
    <link rel="stylesheet" href="/static/assets/vendor/magnific-popup/magnific-popup.css" />
    <link rel="stylesheet" href="/static/assets/vendor/bootstrap-datepicker/css/datepicker3.css" />
    <link rel="stylesheet" href="/static/assets/stylesheets/theme.css" />
    <link rel="stylesheet" href="/static/assets/stylesheets/skins/default.css" />
    <link rel="stylesheet" href="/static/assets/stylesheets/theme-custom.css">
    <script src="/static/assets/vendor/modernizr/modernizr.js"></script>
    <style>
    .list li{float: left}
    </style>

{% endblock %}


{% block content %}
<header class="page-header">
    <h2>站台信息</h2>
    <div class="right-wrapper pull-right">
        <ol class="breadcrumbs">
            <li>
                <a href="/">
                    <i class="fa fa-home"></i>
                </a>
            </li>
            <li><span>站台信息</span></li>
        </ol>
        <a class="sidebar-right-toggle" data-open="sidebar-right"><i class="fa fa-chevron-left"></i></a>
    </div>
</header>

<div class="row">
    <div class="col-md-12">
    <section class="panel">
        <header class="panel-heading">
        <h2 class="panel-title">站台信息展示</h2>
        </header>
        <div class="panel-body">
        <div class="row">
            <div class="col-md-12">
                <div data-collapsed="0" class="panel">
                    <div class="panel-body">
                        <div class="row">
                            <form action="" method="get">
                                <div class="col-md-6 form-group">
                                    <input type="text" placeholder="站点名称" class="form-control" name="site_name" value="{{ site_name }}">
                                </div>
                                <div class="col-md-2 form-group">
                                    <button type="submit" class="form-control btn-primary btn">搜索</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="table-responsive">
            <table class="table table-hover mb-none table-bordered">
                <thead>
                    <tr>
                        <th width="130px">站台名称</th>
                        <th>站台编号</th>
                        <th>经过车辆</th>
                        <th>所属城市</th>
                        <th>操作</th>
                    </tr>
                </thead>
                <tbody>
                {% for site in data %}
                    <tr>
                        <td><a href="{% url 'home:site_detail' site.id %}">{{ site.site_name }}</a></td>
                        <td>
                            {{ site.site_number }}
                        </td>
                        <td>
                            {% for bus in site.bussite_set.all %}
                                <a href="{% url 'home:bus_detail' bus.bus.id%}">
                                {{ bus.bus.bus_name }}/
                                </a>
                            {% endfor %}
                        </td>
                        <td>
                            {{ site.city }}
                        </td>
                        <td><a href="{% url 'home:site_detail' site.id %}" class="btn btn-primary btn-sm">查看详情</a></td>
                        <td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    </section>
    </div>
    <ul class="list">
       {% if data.has_previous %}
        <a href="?page={{ data.previous_page_number }}&site_name={{ site_name }}" class="btn-sm btn">&lt;</a>
        {% endif %}
        {% for page in page_list %}
            {% if request.GET.page %}
                {% if page == request.GET.page|add:0 %}
                    <a href="?page={{ page }}&site_name={{ site_name }}" class="btn-sm btn-success btn">{{ page }}</a>
                {% elif  request.GET.page|add:0 > data.number and page == 1%}
                    <a href="?page={{ page }}&site_name={{ site_name }}" class="btn-sm btn-success btn">{{ page }}</a>
                {% else %}
                    <a href="?page={{ page }}&site_name={{ site_name }}" class="btn-sm btn">{{ page }}</a>
                {% endif %}
            {% else %}
                 {% if page == 1 %}
                    <a href="?page={{ page }}&site_name={{ site_name }}" class="btn-sm btn-success btn">{{ page }}</a>
                    {% else %}
                    <a href="?page={{ page }}&site_name={{ site_name }}" class="btn-sm btn">{{ page }}</a>
                 {% endif %}
            {% endif %}
        {% endfor %}
         {% if data.has_next %}
            <a href="?page={{ data.next_page_number }}&site_name={{ site_name }}" class="btn-sm btn">&gt;</a>
         {% endif %}
    </ul>
</div>

{% endblock %}


{% block script %}
    <script src="/static/assets/vendor/jquery/jquery.js"></script>
    <script src="/static/assets/vendor/jquery-browser-mobile/jquery.browser.mobile.js"></script>
    <script src="/static/assets/vendor/bootstrap/js/bootstrap.js"></script>
    <script src="/static/assets/vendor/nanoscroller/nanoscroller.js"></script>
    <script src="/static/assets/vendor/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>
    <script src="/static/assets/vendor/magnific-popup/magnific-popup.js"></script>
    <script src="/static/assets/vendor/jquery-placeholder/jquery.placeholder.js"></script>
    <script src="/static/assets/javascripts/theme.js"></script>
    <script src="/static/assets/javascripts/theme.custom.js"></script>
    <script src="/static/assets/javascripts/theme.init.js"></script>
{% endblock %}